### PR TITLE
(fix) date comparison bug on the events page

### LINKED ISSUE #28: Use any date library to Compare date.
Change the `compareDate` function present in `src/routes/events.svelte` to compare date using any JS library that handles date. The date data is taken from `static/Data/events.json` with the specific input of `"formatDate": "19-9-2020"`. Right now the compareDate returns `false` even if it is in the future.

### PR DESCRIPTION
**Pull request by aayushmau5**
This should resolve #28

### CODE REVIEW

File: src/routes/events.svelte [hunk 1]
```diff
@@ -38,13 +38,9 @@ onMount(async () => {
...
-  let [prevDate, prevMonth, prevYear] = prevTime.split('-');
-  let [month, date, year] = new Date().toLocaleDateString().split('/');
-  if (+prevDate < +date || +prevMonth < +month || +prevYear < +year) {
-    return false;
-  } else {
-    return true;
-  }
+ const currentDate = new Date();
+ const prevDate = new Date(prevTime);
+ return prevDate <= currentDate ? false : true;
```
Comment (aaryanporwal) [inline src/routes/events.svelte]: remove "=" sign here

**Review by aaryanporwal — APPROVED** [review]

File: src/routes/events.svelte (hunk 1 above)
Comment (aayushmau5) [reply src/routes/events.svelte]: Done.

**Review by aaryanporwal — APPROVED** [review]
